services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
      # This builds a custom Ollama image with nomic-embed-text model pre-installed
    ports:
      - "11434:11434"
    restart: unless-stopped
  mcp-ragdocs:
    build:
      context: .
      dockerfile: Dockerfile
      # Enable BuildKit features
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "3030:3030"
      - "3031:3031"
    depends_on:
      - qdrant
      - ollama
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_PROVIDER=ollama
      - EMBEDDING_MODEL=nomic-embed-text
      - OLLAMA_BASE_URL=http://ollama:11434
